name: Update README

on:
  schedule:
    - cron: '* */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: giaosayago/giaosayago@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
